minetest.register_biome({
    name = "insolated",
    node_top = "froager2:dirt_energized",
    depth_top = 1,
    node_filler = "froager2:dirt",
    depth_filler = 5,
    node_stone = "froager2:stone",
    node_water_top = "",
    depth_water_top = 0,
    node_water = "",
    node_riverbed = "froager2:dirt",
    depth_riverbed = 2,
    node_cave_liquid = "default:lava_source",
    node_cave_liquid = {"default:water_source", "default:lava_source"},
    node_dungeon = "froager2:cobble",
    node_dungeon_alt = "froager2:stone",
    node_dungeon_stair = "",
    y_max = 31000,
    y_min = 1,
    vertical_blend = 8,
    heat_point = 0,
    humidity_point = 50,
})